#!/usr/bin/env node

// Convert WWW files into C strings to avoid FS use in firmware.
//
// in:  build/production
// out: src/www_data.c

const gzip = require('zlib').gzipSync;
const path = require('path');
const read = require('fs').readFileSync;
const write = require('fs').writeFileSync;

const content = read(path.resolve(__dirname, '../build/index.html'));

/*const c_encoded = gzip(content)
  .toString('hex')
  .match(/../g)
  .map(s => `\\x${s.toUpperCase()}`)
  .join('');

const out = `// Autogenerated with 'npm run build', don't change

#ifndef WWW_DATA_HPP
#define WWW_DATA_HPP

const char INDEX_HTML_GZ [] PROGMEM = "${c_encoded}";

#endif
`;

write(path.resolve(__dirname, '../src/firmware/www_data.hpp'), out);*/

write(path.resolve(__dirname, '../src/firmware/data/www/index.html'), content);
write(path.resolve(__dirname, '../src/firmware/data/www/index.html.gz'), gzip(content));
